### ISSUE TITLE
Problem with Predis connection?

### ISSUE THREAD

**Issue by ristokorpela** [opentok/servicekit-php#11]
Hello,
I have now tried to install Servicekit on two different machines with same results,
seems that I have some kind of connection problem.

For example on my linux/Apache server-installation I get this error-message :

"Queue error. Try again later."

On console is this:
*****************
Slim Application Error
The application could not run because of the following error:

Details

Type: Predis\Connection\ConnectionException
Code: 111
Message: Connection refused [tcp://127.0.0.1:6379]
File: /home/videoyht/public_html/vendor/predis/predis/src/Connection/AbstractConnection.php
Line: 168
Trace

#0 /home/videoyht/public_html/vendor/predis/predis/src/Connection/StreamConnection.php(97): Predis\Connection\AbstractConnection->onConnectionError('Connection refu...', 111)
#1 /home/videoyht/public_html/vendor/predis/predis/src/Connection/StreamConnection.php(58): Predis\Connection\StreamConnection->tcpStreamInitializer(Object(Predis\Connection\Parameters))
#2 /home/videoyht/public_html/vendor/predis/predis/src/Connection/AbstractConnection.php(94): Predis\Connection\StreamConnection->createResource()
#3 /home/videoyht/public_html/vendor/predis/predis/src/Connection/StreamConnection.php(158): Predis\Connection\AbstractConnection->connect()
#4 /home/videoyht/public_html/vendor/predis/predis/src/Connection/AbstractConnection.php(193): Predis\Connection\StreamConnection->connect()
#5 /home/videoyht/public_html/vendor/predis/predis/src/Connection/StreamConnection.php(184): Predis\Connection\AbstractConnection->getResource()
#6 /home/videoyht/public_html/vendor/predis/predis/src/Connection/StreamConnection.php(290): Predis\Connection\StreamConnection->write('*2\r\n$4\r\nLPOP\r\n$...')
#7 /home/videoyht/public_html/vendor/predis/predis/src/Connection/AbstractConnection.php(123): Predis\Connection\StreamConnection->writeRequest(Object(Predis\Command\ListPopFirst))
#8 /home/videoyht/public_html/vendor/predis/predis/src/Client.php(326): Predis\Connection\AbstractConnection->executeCommand(Object(Predis\Command\ListPopFirst))
#9 /home/videoyht/public_html/vendor/predis/predis/src/Client.php(310): Predis\Client->executeCommand(Object(Predis\Command\ListPopFirst))
#10 /home/videoyht/public_html/index.php(175): Predis\Client->__call('lpop', Array)
#11 /home/videoyht/public_html/index.php(175): Predis\Client->lpop('helpqueue')
#12 [internal function]: {closure}()
#13 /home/videoyht/public_html/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#14 /home/videoyht/public_html/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#15 /home/videoyht/public_html/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#16 /home/videoyht/public_html/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#17 /home/videoyht/public_html/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#18 /home/videoyht/public_html/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#19 /home/videoyht/public_html/index.php(240): Slim\Slim->run()
#20 {main}
************************************

This comes both on client- and representative -side.
Representative-side seems to work so far that It starts my camera/mic and shows video
and rep login goes ok but when I press "Get Customer" I get "Queue error. Try again later."

You have previously told that included .htaccess -file should be on web root and I have done so.
Because those urls include /home/videoyht and public_html is webroot, does it mean that URL rewriting is not working fully? If I take .htaccess-file away it gives errors already coming to 
web starting-page so it does work at least partially?

Any ideas what could be wrong?

**Comment by ristokorpela** [comment]
I suppose this was in wrong place, I try to add this on community support -pages.
